# Host configuration for FreeBSD.

HOST_CC_DEFAULT=cc
HOST_CXX_DEFAULT=c++
HOST_SHELL_DEFAULT=/usr/local/bin/bash

HOST_INCLUDE="${HOST_PLATFORM_DIR}/include"
HOST_COMPAT="${HOST_PLATFORM_DIR}/compat"

HOST_FEATURE_CPPFLAGS="-I${HOST_INCLUDE}"
HOST_TOOL_CPPFLAGS="${HOST_FEATURE_CPPFLAGS} -idirafter ${SRCDIR}/include"
LLVM_HOST_CPPFLAGS="${HOST_FEATURE_CPPFLAGS}"
LLVM_HOST_LDADD="-lpthread"
BMAKE_LDLIBS=
BMAKE_USE_OPENBSD_GETOPT=no
BMAKE_COMPAT_SRCS="pledge.c"

HOST_TOOL_COMPAT_SRCS="pledge.c unveil.c"
HOST_TOOL_ALLOC_COMPAT_SRCS="${HOST_TOOL_COMPAT_SRCS}"
CONFIG_COMPAT_SRCS="pledge.c"
MAKEFS_COMPAT_SRCS="${HOST_TOOL_COMPAT_SRCS} random.c scan_scaled.c"
MAKE_GENERATOR_COMPAT_SRCS="${SRCDIR}/lib/libutil/ohash.c"
