#!/bin/sh
#
# cross-build-userland.sh - start cross-building OpenBSD userland on Linux.
#
# This builds the foundation libc needs, then recurses through the rest of
# userland using OpenBSD's makefiles and SUBDIR ordering.
#
# Usage:
#   ./bootstrap/cross-build-userland.sh [MACHINE=amd64] [MACHINE_ARCH=amd64]
#
set -e

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
SRCDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

BMAKE="${BMAKE:-${SCRIPTDIR}/tools/bin/bmake}"
TOOLDIR="${TOOLDIR:-${SCRIPTDIR}/tools}"
DESTDIR="${DESTDIR:-${SCRIPTDIR}/dest}"
OBJROOT="${OBJROOT:-${SCRIPTDIR}/obj-host}"
HOST_CLANG_OBJDIR="${HOST_CLANG_OBJDIR:-${SCRIPTDIR}/obj-build/gnu/usr.bin/clang}"

MACHINE="${MACHINE:-amd64}"
MACHINE_ARCH="${MACHINE_ARCH:-amd64}"
MACHINE_CPU="${MACHINE_CPU:-${MACHINE_ARCH}}"
TARGET_CANON="${TARGET_CANON:-${MACHINE_ARCH}-unknown-openbsd7.9}"
BUILD_LLDB="${BUILD_LLDB:-no}"

CLANG="${CLANG:-${TOOLDIR}/bin/clang}"
LLD="${LLD:-${TOOLDIR}/bin/ld.lld}"
AR="${AR:-ar}"
RANLIB="${RANLIB:-ranlib}"
if [ -n "${HOSTCC:-}" ]; then
	HOST_CC="${HOSTCC}"
elif [ -x /usr/bin/cc ]; then
	HOST_CC="/usr/bin/cc"
else
	HOST_CC="cc"
fi

BUILDUSER="${BUILDUSER:-$(id -un)}"
BUILDGROUP="${BUILDGROUP:-$(id -gn)}"

WRAPDIR="${SCRIPTDIR}/wrap"
CROSS_BINDIR="${SCRIPTDIR}/userland-tools/bin"
CROSS_CC="${CROSS_BINDIR}/openbsd-cross-cc"
CROSS_CXX="${CROSS_BINDIR}/openbsd-cross-c++"
CROSS_INSTALL="${CROSS_BINDIR}/openbsd-install"
LLVM_MIN_TBLGEN="${LLVM_MIN_TBLGEN:-${HOST_CLANG_OBJDIR}/llvm-min-tblgen/llvm-min-tblgen}"
LLVM_TBLGEN="${LLVM_TBLGEN:-${HOST_CLANG_OBJDIR}/llvm-tblgen/llvm-tblgen}"
CLANG_TBLGEN="${CLANG_TBLGEN:-${HOST_CLANG_OBJDIR}/clang-tblgen/clang-tblgen}"
LLDB_TBLGEN="${LLDB_TBLGEN:-${HOST_CLANG_OBJDIR}/lldb-tblgen/lldb-tblgen}"

need_tool() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo "missing required host tool: $1" >&2
		exit 1
	fi
}

need_file() {
	if [ ! -x "$1" ]; then
		echo "missing required executable: $1" >&2
		exit 1
	fi
}

need_dir() {
	if [ ! -d "$1" ]; then
		echo "missing required directory: $1" >&2
		exit 1
	fi
}

create_mtree_dirs() {
	awk '
		/^[[:space:]]*(#|$|\/set)/ { next }
		{
			line = $0
			sub(/#.*/, "", line)
			sub(/^[[:space:]]+/, "", line)
			sub(/[[:space:]]+$/, "", line)
			if (line == "")
				next
			split(line, field, /[[:space:]]+/)
			name = field[1]
			if (name == ".")
				next
			if (name == "..") {
				if (depth > 0)
					depth--
				next
			}
			path = ""
			for (i = 0; i < depth; i++)
				path = path stack[i] "/"
			print path name
			stack[depth++] = name
		}
	' "${SRCDIR}/etc/mtree/4.4BSD.dist" | while IFS= read -r dir; do
		mkdir -p "${DESTDIR}/${dir}"
	done
}

need_file "${BMAKE}"
need_file "${CLANG}"
need_file "${LLD}"
need_file "${TOOLDIR}/bin/rpcgen"
need_file "${TOOLDIR}/bin/yacc"
need_file "${LLVM_MIN_TBLGEN}"
need_file "${LLVM_TBLGEN}"
need_file "${CLANG_TBLGEN}"
case "${BUILD_LLDB}" in
[Nn][Oo]) ;;
*) need_file "${LLDB_TBLGEN}" ;;
esac
need_tool install
need_tool pax
need_tool perl
need_tool "${AR}"
need_tool "${RANLIB}"

HOST_INSTALL="$(command -v install)"

CLANG_RESOURCE_INCLUDE="$("${CLANG}" -print-resource-dir)/include"
need_dir "${CLANG_RESOURCE_INCLUDE}"
export CPPFLAGS="-idirafter ${CLANG_RESOURCE_INCLUDE}"

mkdir -p "${CROSS_BINDIR}" \
	"${OBJROOT}"
create_mtree_dirs

BOOTSTRAP_MKCONF="${OBJROOT}/mk.conf"
cat > "${BOOTSTRAP_MKCONF}" <<EOF
# Generated by bootstrap/cross-build-userland.sh.
#
# usr.bin/make builds a small host-side generator before cross-building make
# itself.  On OpenBSD it gets ohash and strtonum from the system libraries;
# on GNU/Linux provide those sources directly through the existing DPADD
# dependency hook used by the generator rule.
.if \${.CURDIR} == "\${BSDSRCDIR}/usr.bin/make"
HOSTCFLAGS+=	-I\${BSDSRCDIR}/bootstrap/include
HOSTCFLAGS+=	-I\${BSDSRCDIR}/lib/libutil
HOSTCFLAGS+=	-D_DEFAULT_SOURCE -Wno-attributes
LIBUTIL=	\${BSDSRCDIR}/lib/libutil/ohash.c \\
		\${BSDSRCDIR}/bootstrap/compat/strtonum.c
.endif

LLVM_MIN_TBLGEN?=	${LLVM_MIN_TBLGEN}
LLVM_TBLGEN?=		${LLVM_TBLGEN}
CLANG_TBLGEN?=		${CLANG_TBLGEN}
LLDB_TBLGEN?=		${LLDB_TBLGEN}
EOF

cat > "${CROSS_CC}" <<EOF
#!/bin/sh
compile_only=no
for arg do
	case "\$arg" in
		-c|-S|-E|-M|-MM) compile_only=yes ;;
	esac
done
if [ "\$compile_only" = yes ]; then
	exec "${CLANG}" --target="${TARGET_CANON}" --sysroot="${DESTDIR}" "\$@"
fi
exec "${CLANG}" --target="${TARGET_CANON}" --sysroot="${DESTDIR}" \
    -fuse-ld="${LLD}" "\$@"
EOF
[ -x "${CROSS_CC}" ] || chmod +x "${CROSS_CC}"

cat > "${CROSS_CXX}" <<EOF
#!/bin/sh
compile_only=no
for arg do
	case "\$arg" in
		-c|-S|-E|-M|-MM) compile_only=yes ;;
	esac
done
if [ "\$compile_only" = yes ]; then
	exec "${CLANG}" --driver-mode=g++ --target="${TARGET_CANON}" \
	    --sysroot="${DESTDIR}" "\$@"
fi
exec "${CLANG}" --driver-mode=g++ --target="${TARGET_CANON}" \
    --sysroot="${DESTDIR}" -fuse-ld="${LLD}" "\$@"
EOF
[ -x "${CROSS_CXX}" ] || chmod +x "${CROSS_CXX}"

cat > "${CROSS_BINDIR}/ctags" <<'EOF'
#!/bin/sh
:
EOF
[ -x "${CROSS_BINDIR}/ctags" ] || chmod +x "${CROSS_BINDIR}/ctags"

cat > "${CROSS_INSTALL}" <<EOF
#!/usr/bin/env bash
#
# OpenBSD makefiles occasionally pass owner/group metadata that is not
# meaningful in an unprivileged Linux DESTDIR.  Drop those requests instead
# of patching individual makefiles.
out=()
while (( \$# )); do
	arg="\$1"
	shift
	case "\$arg" in
		-o)
			shift
			;;
		-o*)
			;;
		--owner)
			shift
			;;
		--owner=*)
			;;
		-g)
			shift
			;;
		-g*)
			;;
		--group)
			shift
			;;
		--group=*)
			;;
		*)
			out+=( "\$arg" )
			;;
	esac
done
exec "${HOST_INSTALL}" "\${out[@]}"
EOF
[ -x "${CROSS_INSTALL}" ] || chmod +x "${CROSS_INSTALL}"
ln -sf openbsd-install "${CROSS_BINDIR}/install"

export PATH="${CROSS_BINDIR}:${TOOLDIR}/bin:${WRAPDIR}:${PATH}"
export MACHINE MACHINE_ARCH MACHINE_CPU

MAKE_ARGS="-m ${SRCDIR}/share/mk -j 16"
MAKEOBJDIR="obj.linux.${MACHINE}"

MAKE_ENV="
	BSDSRCDIR=${SRCDIR}
	BSDOBJDIR=${OBJROOT}
	MAKEOBJDIR=${MAKEOBJDIR}
	CROSSDIR=${DESTDIR}
	DESTDIR=${DESTDIR}
	MACHINE=${MACHINE}
	MACHINE_ARCH=${MACHINE_ARCH}
	MACHINE_CPU=${MACHINE_CPU}
	COMPILER_VERSION=clang
	LINKER_VERSION=lld
	BUILD_CLANG=yes
	BUILD_LLDB=${BUILD_LLDB}
	WARNINGS=no
	NOMAN=1
	NOPROFILE=1
	EXTRA_SYS_MK_INCLUDES=\"${BOOTSTRAP_MKCONF}\"
	MAKECONF=/dev/null
	MAKE=${BMAKE}
	CC=${CROSS_CC}
	CXX=${CROSS_CXX}
	LD=${LLD}
	AR=${AR}
	RANLIB=${RANLIB}
	LORDER=${WRAPDIR}/lorder
	INSTALL=${CROSS_INSTALL}
	HOSTCC=${HOST_CC}
	HOSTCFLAGS=-O2
	CTAGS=true
	BINOWN=${BUILDUSER}
	BINGRP=${BUILDGROUP}
	LIBOWN=${BUILDUSER}
	LIBGRP=${BUILDGROUP}
	SHAREOWN=${BUILDUSER}
	SHAREGRP=${BUILDGROUP}
	MANOWN=${BUILDUSER}
	MANGRP=${BUILDGROUP}
"

run_make() {
	dir="$1"
	shift

	env ${MAKE_ENV} "${BMAKE}" ${MAKE_ARGS} -C "${SRCDIR}/${dir}" "$@"
}

build_install() {
	dir="$1"

	run_make "${dir}" obj
	run_make "${dir}" all
	run_make "${dir}" DESTDIR="${DESTDIR}" install
}

build_subtree() {
	dir="$1"
	shift

	run_make "${dir}" obj "$@"
	run_make "${dir}" all "$@"
	run_make "${dir}" DESTDIR="${DESTDIR}" install "$@"
}

NO_CROSS="${NO_CROSS:-microcode groff binutils binutils-2.17 perl texinfo gcc cvs nsd bind unbound}"
LIB_SKIPDIR="${LIB_SKIPDIR:-csu libc ${NO_CROSS}}"
GNU_LIB_SKIPDIR="${GNU_LIB_SKIPDIR:-libcompiler_rt libexecinfo libiberty libreadline libstdc++-v3 libsupc++-v3}"
GNU_USR_BIN_SKIPDIR="${GNU_USR_BIN_SKIPDIR:-cc cvs binutils binutils-2.17 perl texinfo}"
# Host makeinfo versions may reject legacy OpenBSD texinfo sources.  Info
# pages are not needed for bootstrapping, so skip the amd reference manual.
BIN_SKIPDIR="${BIN_SKIPDIR:-ar as gasp ld nm objcopy objdump ranlib readelf size strings strip amd/doc ${NO_CROSS}}"

echo "==> Cross-building OpenBSD userland"
echo "    SRCDIR       = ${SRCDIR}"
echo "    BMAKE        = ${BMAKE}"
echo "    TARGET       = ${TARGET_CANON}"
echo "    DESTDIR      = ${DESTDIR}"
echo "    OBJROOT      = ${OBJROOT}"
echo "    CC           = ${CROSS_CC}"
echo "    HOSTCC       = ${HOST_CC}"
echo "    LD           = ${LLD}"
echo "    LLVM_TBLGEN  = ${LLVM_TBLGEN}"
echo "    CLANG_TBLGEN = ${CLANG_TBLGEN}"
echo "    LLDB_TBLGEN  = ${LLDB_TBLGEN}"
echo ""

echo "==> Installing headers"
run_make include prereq
run_make include DESTDIR="${DESTDIR}" includes

echo ""
echo "==> Building csu startup objects"
build_install lib/csu

echo ""
echo "==> Building libcompiler_rt"
build_install gnu/lib/libcompiler_rt

echo ""
echo "==> Building libc, including shared libc"
build_install lib/libc

echo ""
echo "==> Building remaining libraries"
build_subtree lib SKIPDIR="${LIB_SKIPDIR}"

echo ""
echo "==> Building userland programs"
for dir in libexec bin sbin usr.bin usr.sbin; do
	build_subtree "${dir}" SKIPDIR="${BIN_SKIPDIR}"
done

echo ""
echo "==> Building GNU libraries needed for clang"
build_subtree gnu/lib SKIPDIR="${GNU_LIB_SKIPDIR}"

echo ""
echo "==> Patching clang Makefiles to use host-native tblgen tools"
"${SCRIPTDIR}/patch-clang-tblgen.sh" "${SRCDIR}/gnu/usr.bin/clang"

echo ""
echo "==> Pre-creating dummy man page for lld (NOMAN build needs it for the ld.1 symlink)"
mkdir -p "${DESTDIR}/usr/share/man/man1"
touch "${DESTDIR}/usr/share/man/man1/ld.lld.1"

echo ""
echo "==> Building OpenBSD-native clang"
# After libcxx/libcxxabi are built, add the installed C++ headers to the
# include path so programs (clang, lld) can find <vector>, <cstddef>, etc.
# Use -isystem (not -idirafter) so libcxx wrapper headers are found before
# system headers — this lets <cstddef>'s #include <stddef.h> find the
# wrapper, which then #include_next's to the real system header.
export CXXFLAGS="-O2 -pipe -g -isystem ${DESTDIR}/usr/include/c++/v1"
build_subtree gnu/usr.bin SKIPDIR="${GNU_USR_BIN_SKIPDIR}"

echo ""
echo "==> Success: userland has been built and installed into ${DESTDIR}"
