#!/bin/sh
#
# cross-build-userland.sh - cross-build and stage OpenBSD userland.
#
# This builds the foundation libc needs, then recurses through the rest of
# userland using OpenBSD's makefiles and SUBDIR ordering.
#
# Usage: OBJDIR=/path ./bootstrap/cross-build-userland.sh
#
set -e

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
SRCDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

MACHINE="${MACHINE:-amd64}"
MACHINE_ARCH="${MACHINE_ARCH:-amd64}"
MACHINE_CPU="${MACHINE_CPU:-${MACHINE_ARCH}}"
. "${SCRIPTDIR}/lib.sh"

OBJROOT="${OBJROOT:-${TARGET_OBJDIR}}"
OBJROOT="$(bootstrap_real_dir "${OBJROOT}")"
DESTDIR="${DESTDIR:-${OBJDIR}/dest-${MACHINE}}"
DESTDIR="$(bootstrap_real_dir "${DESTDIR}")"
HOST_CLANG_OBJDIR="${HOST_CLANG_OBJDIR:-${HOST_OBJDIR}/gnu/usr.bin/clang}"

TARGET_CANON="${TARGET_CANON:-${MACHINE_ARCH}-unknown-openbsd7.9}"
BUILD_LLDB="${BUILD_LLDB:-no}"

CLANG="${CLANG:-${TOOLDIR}/bin/clang}"
LLD="${LLD:-${TOOLDIR}/bin/ld.lld}"
AR="${AR:-ar}"
RANLIB="${RANLIB:-ranlib}"

TARGET_TOOLDIR="${TARGET_TOOLDIR:-${OBJDIR}/target-tools-${MACHINE}}"
CROSS_BINDIR="${TARGET_TOOLDIR}/bin"
CROSS_CC="${CROSS_BINDIR}/openbsd-cross-cc"
CROSS_CXX="${CROSS_BINDIR}/openbsd-cross-c++"
CROSS_INSTALL="${CROSS_BINDIR}/openbsd-install"
LLVM_MIN_TBLGEN="${LLVM_MIN_TBLGEN:-${HOST_CLANG_OBJDIR}/llvm-min-tblgen/llvm-min-tblgen}"
LLVM_TBLGEN="${LLVM_TBLGEN:-${HOST_CLANG_OBJDIR}/llvm-tblgen/llvm-tblgen}"
CLANG_TBLGEN="${CLANG_TBLGEN:-${HOST_CLANG_OBJDIR}/clang-tblgen/clang-tblgen}"
LLDB_TBLGEN="${LLDB_TBLGEN:-${HOST_CLANG_OBJDIR}/lldb-tblgen/lldb-tblgen}"

need_dir() {
	if [ ! -d "$1" ]; then
		echo "missing required directory: $1" >&2
		exit 1
	fi
}

create_mtree_dirs() {
	awk '
		/^[[:space:]]*(#|$|\/set)/ { next }
		{
			line = $0
			sub(/#.*/, "", line)
			sub(/^[[:space:]]+/, "", line)
			sub(/[[:space:]]+$/, "", line)
			if (line == "")
				next
			split(line, field, /[[:space:]]+/)
			name = field[1]
			if (name == ".")
				next
			if (name == "..") {
				if (depth > 0)
					depth--
				next
			}
			path = ""
			for (i = 0; i < depth; i++)
				path = path stack[i] "/"
			print path name
			stack[depth++] = name
		}
	' "${SRCDIR}/etc/mtree/4.4BSD.dist" | while IFS= read -r dir; do
		mkdir -p "${DESTDIR}/${dir}"
	done
}

bootstrap_need_exec "${BMAKE}"
bootstrap_need_exec "${CLANG}"
bootstrap_need_exec "${LLD}"
bootstrap_need_exec "${TOOLDIR}/bin/rpcgen"
bootstrap_need_exec "${TOOLDIR}/bin/yacc"
bootstrap_need_exec "${LLVM_MIN_TBLGEN}"
bootstrap_need_exec "${LLVM_TBLGEN}"
bootstrap_need_exec "${CLANG_TBLGEN}"
case "${BUILD_LLDB}" in
[Nn][Oo]) ;;
*) bootstrap_need_exec "${LLDB_TBLGEN}" ;;
esac
bootstrap_need_tool install
bootstrap_need_tool pax
bootstrap_need_tool perl
bootstrap_need_tool "${AR}"
bootstrap_need_tool "${RANLIB}"

HOST_INSTALL="$(command -v install)"

CLANG_RESOURCE_INCLUDE="$("${CLANG}" -print-resource-dir)/include"
need_dir "${CLANG_RESOURCE_INCLUDE}"
export CPPFLAGS="-idirafter ${CLANG_RESOURCE_INCLUDE}"

mkdir -p "${CROSS_BINDIR}" \
	"${OBJROOT}"
create_mtree_dirs

BOOTSTRAP_MKCONF="${OBJROOT}/mk.conf"
cat > "${BOOTSTRAP_MKCONF}" <<EOF
# Generated by bootstrap/cross-build-userland.sh.
#
# usr.bin/make builds a small host-side generator before cross-building make
# itself.  Supply OpenBSD ohash and any interfaces missing from the host libc
# through the existing DPADD dependency hook used by the generator rule.
.if \${.CURDIR} == "\${BSDSRCDIR}/usr.bin/make"
HOSTCFLAGS+=	${HOST_FEATURE_CPPFLAGS}
HOSTCFLAGS+=	-I\${BSDSRCDIR}/lib/libutil
LIBUTIL=	${MAKE_GENERATOR_COMPAT_SRCS}
.endif

LLVM_MIN_TBLGEN?=	${LLVM_MIN_TBLGEN}
LLVM_TBLGEN?=		${LLVM_TBLGEN}
CLANG_TBLGEN?=		${CLANG_TBLGEN}
LLDB_TBLGEN?=		${LLDB_TBLGEN}
EOF

bootstrap_write_cross_cc \
	"${CROSS_CC}" "${CLANG}" "${TARGET_CANON}" "${DESTDIR}" "${LLD}"
bootstrap_write_cross_cc \
	"${CROSS_CXX}" "${CLANG}" "${TARGET_CANON}" "${DESTDIR}" "${LLD}" g++

cat > "${CROSS_BINDIR}/ctags" <<'EOF'
#!/bin/sh
:
EOF
[ -x "${CROSS_BINDIR}/ctags" ] || chmod +x "${CROSS_BINDIR}/ctags"

bootstrap_write_install "${CROSS_INSTALL}" "${HOST_INSTALL}"
ln -sf openbsd-install "${CROSS_BINDIR}/install"

export PATH="${CROSS_BINDIR}:${TOOLDIR}/bin:${WRAPDIR}:${PATH}"
export MACHINE MACHINE_ARCH MACHINE_CPU

MAKEOBJDIR="${MAKEOBJDIR:-obj.cross.${MACHINE}}"

MAKE_ENV="
	BSDSRCDIR=${SRCDIR}
	BSDOBJDIR=${OBJROOT}
	MAKEOBJDIR=${MAKEOBJDIR}
	CROSSDIR=${DESTDIR}
	DESTDIR=${DESTDIR}
	MACHINE=${MACHINE}
	MACHINE_ARCH=${MACHINE_ARCH}
	MACHINE_CPU=${MACHINE_CPU}
	COMPILER_VERSION=clang
	LINKER_VERSION=lld
	BUILD_CLANG=yes
	BUILD_LLDB=${BUILD_LLDB}
	WARNINGS=no
	NOMAN=1
	NOPROFILE=1
	EXTRA_SYS_MK_INCLUDES=\"${BOOTSTRAP_MKCONF}\"
	MAKECONF=/dev/null
	MAKE=${BMAKE}
	CC=${CROSS_CC}
	CXX=${CROSS_CXX}
	LD=${LLD}
	AR=${AR}
	RANLIB=${RANLIB}
	LORDER=${WRAPDIR}/lorder
	INSTALL=${CROSS_INSTALL}
	HOSTCC=${HOST_CC}
	HOSTCFLAGS=-O2
	CTAGS=true
	BUILDUSER=${HOST_USER}
	BINOWN=${HOST_USER}
	BINGRP=${HOST_GROUP}
	LIBOWN=${HOST_USER}
	LIBGRP=${HOST_GROUP}
	SHAREOWN=${HOST_USER}
	SHAREGRP=${HOST_GROUP}
	MANOWN=${HOST_USER}
	MANGRP=${HOST_GROUP}
"

run_make() {
	dir="$1"
	shift

	env ${MAKE_ENV} "${BMAKE}" ${MAKE_ARGS} -C "${SRCDIR}/${dir}" "$@"
}

build_install() {
	dir="$1"

	run_make "${dir}" obj
	run_make "${dir}" all
	run_make "${dir}" DESTDIR="${DESTDIR}" install
}

build_subtree() {
	dir="$1"
	shift

	run_make "${dir}" obj "$@"
	run_make "${dir}" all "$@"
	run_make "${dir}" DESTDIR="${DESTDIR}" install "$@"
}

NO_CROSS="${NO_CROSS:-microcode groff binutils binutils-2.17 perl texinfo gcc cvs nsd bind unbound}"
LIB_SKIPDIR="${LIB_SKIPDIR:-csu libc ${NO_CROSS}}"
GNU_LIB_SKIPDIR="${GNU_LIB_SKIPDIR:-libcompiler_rt libexecinfo libiberty libreadline libstdc++-v3 libsupc++-v3}"
GNU_USR_BIN_SKIPDIR="${GNU_USR_BIN_SKIPDIR:-cc cvs binutils binutils-2.17 perl texinfo}"
# Host makeinfo versions may reject legacy OpenBSD texinfo sources.  Info
# pages are not needed for bootstrapping, so skip the amd reference manual.
BIN_SKIPDIR="${BIN_SKIPDIR:-ar as gasp ld nm objcopy objdump ranlib readelf size strings strip amd/doc ${NO_CROSS}}"

echo "==> Cross-building OpenBSD userland"
echo "    SRCDIR       = ${SRCDIR}"
echo "    BMAKE        = ${BMAKE}"
echo "    TARGET       = ${TARGET_CANON}"
echo "    DESTDIR      = ${DESTDIR}"
echo "    OBJROOT      = ${OBJROOT}"
echo "    CC           = ${CROSS_CC}"
echo "    HOSTCC       = ${HOST_CC}"
echo "    LD           = ${LLD}"
echo "    LLVM_TBLGEN  = ${LLVM_TBLGEN}"
echo "    CLANG_TBLGEN = ${CLANG_TBLGEN}"
echo "    LLDB_TBLGEN  = ${LLDB_TBLGEN}"
echo ""

echo "==> Preparing object directories"
run_make . obj

echo ""
echo "==> Installing headers"
run_make include prereq
run_make include DESTDIR="${DESTDIR}" includes

echo ""
echo "==> Building csu startup objects"
build_install lib/csu

echo ""
echo "==> Building libcompiler_rt"
build_install gnu/lib/libcompiler_rt

echo ""
echo "==> Building libc, including shared libc"
build_install lib/libc

echo ""
echo "==> Building remaining libraries"
build_subtree lib SKIPDIR="${LIB_SKIPDIR}"

echo ""
echo "==> Building userland programs"
for dir in libexec bin sbin usr.bin usr.sbin; do
	build_subtree "${dir}" SKIPDIR="${BIN_SKIPDIR}"
done

echo ""
echo "==> Building GNU libraries needed for clang"
build_subtree gnu/lib SKIPDIR="${GNU_LIB_SKIPDIR}"

echo ""
echo "==> Patching clang Makefiles to use host-native tblgen tools"
"${SCRIPTDIR}/patch-clang-tblgen.sh" "${SRCDIR}/gnu/usr.bin/clang"

echo ""
echo "==> Pre-creating dummy man page for lld (NOMAN build needs it for the ld.1 symlink)"
mkdir -p "${DESTDIR}/usr/share/man/man1"
touch "${DESTDIR}/usr/share/man/man1/ld.lld.1"

echo ""
echo "==> Building OpenBSD-native clang"
# After libcxx/libcxxabi are built, add the installed C++ headers to the
# include path so programs (clang, lld) can find <vector>, <cstddef>, etc.
# Use -isystem (not -idirafter) so libcxx wrapper headers are found before
# system headers — this lets <cstddef>'s #include <stddef.h> find the
# wrapper, which then #include_next's to the real system header.
export CXXFLAGS="-O2 -pipe -g -isystem ${DESTDIR}/usr/include/c++/v1"
build_subtree gnu/usr.bin SKIPDIR="${GNU_USR_BIN_SKIPDIR}"

echo ""
echo "==> Success: userland has been built and installed into ${DESTDIR}"
