#!/bin/sh
#
# Run make targets in a bootstrapped cross-built kernel directory.
#
# Usage:
#   ./bootstrap/kernel-make.sh [make-target ...]
#   ./bootstrap/kernel-make.sh avl.o
#
# The kernel configuration is regenerated by default so newly-added entries in
# sys/zfs/files.zfs are immediately available.  Set KERNEL_RECONFIG=no to skip
# that step.

set -e

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
SRCDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

BMAKE="${BMAKE:-${SCRIPTDIR}/tools/bin/bmake}"
TOOLDIR="${TOOLDIR:-${SCRIPTDIR}/tools}"
CONFIG_BIN="${CONFIG_BIN:-${TOOLDIR}/bin/config}"
OBJROOT="${OBJROOT:-${SCRIPTDIR}/obj-host}"

MACHINE="${MACHINE:-amd64}"
MACHINE_ARCH="${MACHINE_ARCH:-amd64}"
MACHINE_CPU="${MACHINE_CPU:-${MACHINE_ARCH}}"
KERNEL_CONFIG="${KERNEL_CONFIG:-GENERIC.MP}"
JOBS="${JOBS:-16}"

KERNEL_BINDIR="${SCRIPTDIR}/kernel-tools/bin"
KERNEL_CC="${CC:-${KERNEL_BINDIR}/openbsd-kernel-cc}"
LD="${LD:-${TOOLDIR}/bin/ld.lld}"
MAKEGAP_SRC="${SCRIPTDIR}/makegap-linux.sh"

if [ -n "${HOSTCC:-}" ]; then
	HOST_CC="${HOSTCC}"
elif [ -x /usr/bin/cc ]; then
	HOST_CC=/usr/bin/cc
else
	HOST_CC=cc
fi

BUILDUSER="${BUILDUSER:-$(id -un)}"
BUILDGROUP="${BUILDGROUP:-$(id -gn)}"

CONFIG_SRC="${SRCDIR}/sys/arch/${MACHINE}/conf/${KERNEL_CONFIG}"
KERNEL_BUILDDIR="${OBJROOT}/sys/arch/${MACHINE}/compile/${KERNEL_CONFIG}"
KERNEL_MKCONF="${KERNEL_BUILDDIR}/Makefile.mk.conf"

for tool in "${BMAKE}" "${CONFIG_BIN}" "${KERNEL_CC}" "${LD}"; do
	if [ ! -x "${tool}" ]; then
		echo "missing required executable: ${tool}" >&2
		echo "run ./bootstrap/cross-build-kernel.sh once to create the tool wrappers" >&2
		exit 1
	fi
done

if [ ! -f "${MAKEGAP_SRC}" ]; then
	echo "missing Linux-compatible makegap script: ${MAKEGAP_SRC}" >&2
	exit 1
fi

if [ ! -f "${CONFIG_SRC}" ]; then
	echo "missing kernel configuration: ${CONFIG_SRC}" >&2
	exit 1
fi

if [ "${KERNEL_RECONFIG:-yes}" != no ] || \
    [ ! -f "${KERNEL_BUILDDIR}/Makefile" ]; then
	mkdir -p "${KERNEL_BUILDDIR}"
	"${CONFIG_BIN}" -b "${KERNEL_BUILDDIR}" -s "${SRCDIR}/sys" \
	    "${CONFIG_SRC}"
fi

# Native makegap.sh relies on OpenBSD's sysctl(8) and jot(1).  Install the
# Linux-hosted replacement in every configuration's build directory, not just
# the one initially created by cross-build-kernel.sh.
if [ ! -f "${KERNEL_BUILDDIR}/makegap.sh" ] ||
    ! cmp -s "${MAKEGAP_SRC}" "${KERNEL_BUILDDIR}/makegap.sh"; then
	cp "${MAKEGAP_SRC}" "${KERNEL_BUILDDIR}/makegap.sh"
fi

KERNEL_MKCONF_TMP="$(mktemp "${KERNEL_MKCONF}.XXXXXX")"
cat > "${KERNEL_MKCONF_TMP}" <<'EOF'
makegap.sh:
	@true
EOF
mv "${KERNEL_MKCONF_TMP}" "${KERNEL_MKCONF}"

if [ "$#" -eq 0 ]; then
	set -- all
fi

export PATH="${KERNEL_BINDIR}:${TOOLDIR}/bin:${SCRIPTDIR}/wrap:${PATH}"

exec env \
    BSDSRCDIR="${SRCDIR}" \
    BSDOBJDIR="${OBJROOT}" \
    MACHINE="${MACHINE}" \
    MACHINE_ARCH="${MACHINE_ARCH}" \
    MACHINE_CPU="${MACHINE_CPU}" \
    COMPILER_VERSION=clang \
    LINKER_VERSION=lld \
    WARNINGS=no \
    NOMAN=1 \
    NOPROFILE=1 \
    MAKECONF="${KERNEL_MKCONF}" \
    MAKE="${BMAKE}" \
    CC="${KERNEL_CC}" \
    LD="${LD}" \
    STRIP="${KERNEL_BINDIR}/openbsd-strip-noop" \
    SIZE=size \
    HOSTCC="${HOST_CC}" \
    BINOWN="${BUILDUSER}" \
    BINGRP="${BUILDGROUP}" \
    LIBOWN="${BUILDUSER}" \
    LIBGRP="${BUILDGROUP}" \
    SHAREOWN="${BUILDUSER}" \
    SHAREGRP="${BUILDGROUP}" \
    MANOWN="${BUILDUSER}" \
    MANGRP="${BUILDGROUP}" \
    "${BMAKE}" -m "${SRCDIR}/share/mk" -j "${JOBS}" \
    -C "${KERNEL_BUILDDIR}" "$@"
