#	$OpenBSD$

.include "../Makefile.inc"

LIB=	zfs_core
SRCS=	libzfs_core.c libzfs_core_ioctl.c

.PATH:	${ZFS_SRCS}/lib/libzfs_core \
	${ZFS_SRCS}/lib/libzfs_core/os/openbsd

install:

.include <bsd.lib.mk>
