#	$OpenBSD: Makefile,v 1.16 2026/04/06 10:50:59 kettenis Exp $

MAN=	intro.4 mpfclock.4 mpfgpio.4 mpfiic.4 plic.4 \
	sfcc.4 sfclock.4 sfgpio.4 sfuart.4 sgmsi.4 \
	smtclock.4 smtcomphy.4 smtgpio.4 smtiic.4 \
	stfclock.4 stfpcie.4 stfpciephy.4 stfpinctrl.4 stfrng.4

MANSUBDIR=riscv64

.include <bsd.prog.mk>
