#!/bin/sh
#
# Compiler wrapper that filters out OpenBSD-specific flags unknown to
# upstream clang.  Set REAL_CXX in the environment to override the
# default compiler path.
#
: ${REAL_CXX:=clang++}

for arg; do
	case "$arg" in
		-fno-ret-protector) ;;
		-nopie) set -- "$@" "-no-pie" ;;
		*) set -- "$@" "$arg" ;;
	esac
	shift
done

exec "${REAL_CXX}" "$@"
